# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_plane/raft/rpc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'control_plane/raft/rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ontrol_plane/raft/rpc.proto\x12\nvault.raft\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"=\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x11\n\targs_json\x18\x03 \x01(\t\"\xa4\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x03\x12\x15\n\rprev_log_term\x18\x04 \x01(\x03\x12%\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x14.vault.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x03\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xac\x01\n\x04Raft\x12N\n\x0bRequestVote\x12\x1e.vault.raft.RequestVoteRequest\x1a\x1f.vault.raft.RequestVoteResponse\x12T\n\rAppendEntries\x12 .vault.raft.AppendEntriesRequest\x1a!.vault.raft.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_plane.raft.rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=44
  _globals['_REQUESTVOTEREQUEST']._serialized_end=147
  _globals['_REQUESTVOTERESPONSE']._serialized_start=149
  _globals['_REQUESTVOTERESPONSE']._serialized_end=206
  _globals['_LOGENTRY']._serialized_start=208
  _globals['_LOGENTRY']._serialized_end=269
  _globals['_APPENDENTRIESREQUEST']._serialized_start=272
  _globals['_APPENDENTRIESREQUEST']._serialized_end=436
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=438
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=492
  _globals['_RAFT']._serialized_start=495
  _globals['_RAFT']._serialized_end=667
# @@protoc_insertion_point(module_scope)
